config/routes.rb
Judesapp::Application.routes.draw do

  get 'sitemap' => "sitemap#index"

    root :to => 'pages#home'
    get "pages/home"
    get "pages/about"
    get "sessions/new"
    get 'login'  => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy' , :as => :logout
    get 'signup' => 'users#new'
    get "pages/sign_in"
    get "pages/help"

  resources :users
  resources :training_events
  resources :attends
  resources :players
  resources :session, :only => [:new, :create, :destroy]
  resources :sitemaps

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

end

app/models/training_event.rb
class TrainingEvent < ActiveRecord::Base
  attr_accessible  :training_location,:training_date,:training_type,:duration


  validates :training_location, presence: true, length: {maximum: 50}
  validates :training_type, presence: true, length: {maximum: 30}
  validates :training_date, presence: true
  validates :duration, presence: true

  has_many :attends
	has_many :players, :through => :attends


end

app/controllers/training_events_controller.rb
class TrainingEventsController < ApplicationController

 # authenticate :user do
 #   resources :training_events, only: [:new, :create, :edit, :update, :destroy]
 # end


  # GET /training_events
  # GET /training_events.json
  def index
    @training_events = TrainingEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @training_events }
    end
  end

  def player
    player = Player.find(:player_id)
  end

  def training_event
    @training_event = TrainingEvent.find(:player_id)
  end
  # GET /training_events/1
  # GET /training_events/1.json
  def show
    @training_event = TrainingEvent.find(params[:id])

    @attendance = Attend.where(training_event_id:  @training_event.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @training_event }
    end
  end


  # GET /training_events/new
  # GET /training_events/new.json
  def new
    @training_event = TrainingEvent.new

    #======================
    @all_training_events = TrainingEvent.all
    @all_players = Player.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @training_event }
    end
  end

  # GET /training_events/1/edit
  def edit
    @training_event = TrainingEvent.find(params[:id])
  end

  # POST /training_events
  # POST /training_events.json
  def create
    @training_event = TrainingEvent.new(params[:training_event])

    respond_to do |format|
      if @training_event.save
        format.html { redirect_to @training_event, notice: 'Training event was successfully created.' }
        format.json { render json: @training_event, status: :created, location: @training_event }
      else
        format.html { render action: "new" }
        format.json { render json: @training_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /training_events/1
  # PUT /training_events/1.json
  def update
    @training_event = TrainingEvent.find(params[:id])

    respond_to do |format|
      if @training_event.update_attributes(params[:training_event])
        format.html { redirect_to @training_event, notice: 'Training event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @training_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_events/1
  # DELETE /training_events/1.json
  def destroy
    @training_event = TrainingEvent.find(params[:id])
    @training_event.destroy

    respond_to do |format|
      format.html { redirect_to training_events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/training_events_helper.rb
module TrainingEventsHelper
end

app/views/training_events/_form.html.erb
<%= form_for(@training_event) do |f| %>
  <% if @training_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training_event.errors.count, "error") %> prohibited this training_event from being saved:</h2>

      <ul>
      <% @training_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div align="center">
      <div class="field">
        <%= f.label :training_date %><br />
        <%= f.date_select :training_date %>
      </div>
      <div class="field">
        <%= f.label :duration %><br />
        <%= f.number_field :duration %>
      </div>


      <div class="control-group">
        <%= f.label :training_location, class: 'control-label' %><br />
        <div class="controls">
           <%= f.select(:training_location, options_for_select(
                      [
                      ["Pitch 1","Pitch 1"],["Pitch 2","Pitch 2"],["Pitch 3","Pitch 3"],["Pitch 4","Pitch 4"],
                      ["Hurling Alley","Hurling Alley"], ["All-Weather-Pitch","All-Weather-Pitch"],["Hall","Hall"],["Gym","Gym"]
                      ]))
            %>
        </div>
      </div>

      <div class="control-group">
        <br/>
        <%= f.label :training_type, class: 'control-label' %><br />

        <div class="controls">

            <%= f.select(:training_type, options_for_select(
                     [
                      ["Fitness","Fitness"],
                      ["Strength & Conditioning","Strength & Conditioning"],
                      ["Technical Work","Technical Work"],
                      ["Challenge Match","Challenge Match"],
                      ["Fitness & Technical","Fitness & Technical"],
                      ["HIIT & Technical","HIIT & Technical"],
                      ]))
             %>
        </div>
      </div>


      <br/>
        <div class="actions">
        <%= f.submit %>
      </div>
  
    <% end %>
</div>

app/views/training_events/_formNew.html.erb
<%= form_for(@training_event) do |f| %>
  <% if @training_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training_event.errors.count, "error") %> prohibited this training_event from being saved:</h2>

      <ul>
      <% @training_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div align="center">
      <div style="width: 50%; height: 50%; background-color: white;" class="round">
        <br>
        <div  class="field" >
        <%= f.date_select :training_date, {:prompt => 'Training Date'} %>
        <%= f.number_field :duration, :placeholder => "Duration (Minutes)" %>
        <%= f.select(:training_location, options_for_select(
                  [
                  ["Pitch 1","Pitch 1"],["Pitch 2","Pitch 2"],["Pitch 3","Pitch 3"],["Pitch 4","Pitch 4"],
                  ["Hurling Alley","Hurling Alley"], ["All-Weather-Pitch","All-Weather-Pitch"],["Hall","Hall"],["Gym","Gym"]
                  ]), {:prompt => 'Location'})
        %>
        <%= f.select(:training_type, options_for_select(
                 [
                  ["Fitness","Fitness"],
                  ["Strength & Conditioning","Strength & Conditioning"],
                  ["Technical Work","Technical Work"],
                  ["Challenge Match","Challenge Match"],
                  ["Fitness & Technical","Fitness & Technical"],
                  ["HIIT & Technical","HIIT & Technical"],
                  ]), {:prompt => 'Training Type'})
         %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
<% end %>
</div>

app/views/training_events/_formUpdate.html.erb
<%= form_for(@training_event) do |f| %>
  <% if @training_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training_event.errors.count, "error") %> prohibited this training_event from being saved:</h2>

      <ul>
      <% @training_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div align="center">
      <div style="width: 50%; height: 50%; background-color: white;" class="round">
        <br>
        <div  class="field" >
        <%= f.date_select :training_date, {:prompt => 'Training Date'} %>
        <%= f.number_field :duration, :placeholder => "Duration (Minutes)" %>
        <%= f.select(:training_location, options_for_select(
                  [
                  ["Pitch 1","Pitch 1"],["Pitch 2","Pitch 2"],["Pitch 3","Pitch 3"],["Pitch 4","Pitch 4"],
                  ["Hurling Alley","Hurling Alley"], ["All-Weather-Pitch","All-Weather-Pitch"],["Hall","Hall"],["Gym","Gym"]
                  ]), {:prompt => 'Location'})
        %>
        <%= f.select(:training_type, options_for_select(
                 [
                  ["Fitness","Fitness"],
                  ["Strength & Conditioning","Strength & Conditioning"],
                  ["Technical Work","Technical Work"],
                  ["Challenge Match","Challenge Match"],
                  ["Fitness & Technical","Fitness & Technical"],
                  ["HIIT & Technical","HIIT & Technical"],
                  ]), {:prompt => 'Training Type'})
         %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
<% end %>
</div>

app/views/training_events/edit.html.erb
<br>
<h1>Editing Training Event</h1>

<%= render 'formUpdate' %>

<%= link_to 'Show', @training_event %> |
<%= link_to 'Back', training_events_path %>

app/views/training_events/index.html.erb
<br>
<h1>Listing Training Events</h1>

<table id="listing" class="<%= cycle('even', 'odd') -%>">
  <tr>

    <th>Training location</th>
    <th>Training type</th>
    <th>Training date</th>
    <th>Duration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @training_events.each do |training_event| %>
      <tr class="<%= cycle("odd_row", "even_row", name: "row_class") -%>">

            <td><%= training_event.training_location %></td>
            <td><%= training_event.training_type %></td>
            <td><%= training_event.training_date %></td>
            <td><%= training_event.duration %></td>
            <td><%= link_to 'Show', training_event %></td>
            <td><%= link_to 'Edit', edit_training_event_path(training_event) %></td>
            <td><%= link_to 'Destroy', training_event, confirm: 'Are you sure?', method: :delete %></td>

      </tr>
<% end %>
</table>

<br />

<%= link_to 'New Training Event', new_training_event_path %>

app/views/training_events/new.html.erb
<br>
<h1>New Training Event</h1>

<%= render 'formNew' %>

<%= link_to 'Back', training_events_path %>

app/views/training_events/show.html.erb
<br>
<p id="notice"><%= notice %></p>
<table id="listing">
  <tr class=>
    <td class=><b>Training location:</b></td>
    <td class=><%= @training_event.training_location %></td>
  </tr>
  <tr class=>
    <td class=><b>Training type:</b></td>
    <td class=><%= @training_event.training_type %></td>
  </tr>
  <tr class=>
    <td class=><b>raining date:</b></td>
    <td class=> <%= @training_event.training_date.to_s(:long_ordinal) %></td>
  </tr>
  <tr class=>
    <td class=><b>Duration:</b></td>
    <td class=><%= @training_event.duration %></td>
  </tr>
</table>
<br>



<h3>Players Attended</h3>
<table id="listing">
  <tr>
    <th>Player Name</th>
    <th>Address</th>
    <th>Email Address</th>
    <th>Phone Number</th>
  </tr>
  <% @attendance.each do |att| %>
      <tr>
        <td><%= att.player.name %></td>
        <td><%= att.player.address %></td>
        <td><%= att.player.email %></td>
        <td><%= att.player.phone %></td>

      </tr>
  <% end %>
</table>

<br>
<br>
<%= link_to 'Edit', edit_training_event_path(@training_event) %> |
<%= link_to 'Back', training_events_path %>