config/routes.rb
Judesapp::Application.routes.draw do

  get 'sitemap' => "sitemap#index"

    root :to => 'pages#home'
    get "pages/home"
    get "pages/about"
    get "sessions/new"
    get 'login'  => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy' , :as => :logout
    get 'signup' => 'users#new'
    get "pages/sign_in"
    get "pages/help"

  resources :users
  resources :training_events
  resources :attends
  resources :players
  resources :session, :only => [:new, :create, :destroy]
  resources :sitemaps

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

end

app/models/player.rb
class Player < ActiveRecord::Base
	attr_accessible :name, :email, :phone, :address

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence:  true, uniqueness: true, length:  { minimum:  3, maximum:  30 }
  validates :address, length: {minimum: 10, maximum: 150}
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, length:  { minimum: 8, maximum: 50 }
  validates :phone, length: {minimum: 7,  maximum: 15}

  has_many :attends
	has_many :training_events, :through => :attends

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

 # authenticate :user do
 #   resources :players, only: [:new, :create, :edit, :update, :destroy, :show, :index]
 # end



  # GET /players
  # GET /players.json
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end



  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])
    @attendance = Attend.where(player_id:  @player.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json

  def new
    @player = Player.new
    #@all_training_events = TrainingEvent.all
    #@player_training_event = @player.attends.build

	respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end


	end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

	  #params[:training_events][:id].each do |training_event|
    #  if !training_event.empty?
    #    @player.attends.build(:training_event_id => training_event)
    #  end
    #end


    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div align="center">
      <div align="center" class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :phone %>
        <%= f.text_field :phone %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
</div>

app/views/players/_formNew.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div align="center" >
    <div style="width: 50%; height: 50%; background-color: white;" class="round">
      <div align="center" class="field" >
        <br>
        <%= f.text_field :name, :placeholder => "Name" %>
        <%= f.text_field :address, :placeholder => "Address"%>
        <%= f.text_field :email, :placeholder => "Email Address" %>
        <%= f.text_field :phone, :placeholder => "Phone Number" %>

      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
    <% end %>
</div>

app/views/players/_formUpdate.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div align="center" ;>
      <div style="width: 50%; height: 50%; background-color: white;" class="round">
        <br>
        <div  class="field" >

            <%= f.text_field :name, :placeholder => "Name" %>
            <%= f.text_field :address, :placeholder => "Address"%>
            <%= f.text_field :email, :placeholder => "Email Address" %>
            <%= f.text_field :phone, :placeholder => "Phone Number" %>

        </div>
        <div class="actions">
          <%= f.submit :value => "Update Player Details" %>
        </div>
      </div>
    </div>
<% end %>

app/views/players/edit.html.erb
<br>
<h1>Edit Player</h1>

<%= render 'formUpdate' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<br>
<h1>Listing Players</h1>

<table id="listing">
    <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
    </tr>

    <% @players.each do |player| %>
          <tr class="<%= cycle("odd_row", "even_row", name: "row_class") -%>">
            <td><%= player.name %></td>
            <td><%= player.address %></td>
            <td><%= player.email %></td>
            <td><%= player.phone %></td>
            <td><%= link_to 'Show', player %></td>
            <td><%= link_to 'Edit', edit_player_path(player) %></td>
            <td><%= link_to 'Destroy', player, confirm: 'Are you sure?', method: :delete %></td>
          </tr>
    <% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<br>
<h1>New Player</h1>

<%= render 'formNew' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<br>
<p id="notice"><%= notice %></p>
  <table id="listing">
    <tr class=>
      <td class=><b>Name:</b></td>
      <td class=><%= @player.name %></td>
    </tr>
    <tr class=>
      <td class=><b>Address:</b></td>
      <td ><%= @player.address %></td>
    </tr>
    <tr class=>
      <td class=><b>Email:</b></td>
      <td class=> <%= @player.email %></td>
    </tr>
    <tr class=>
      <td class=><b>Phone:</b></td>
      <td class=><%= @player.phone %></td>
    </tr>
  </table>
<br>




<h3>Training Events Attended</h3>
<table id="listing">
  <tr>
      <th>Training Date</th>
      <th>Attendance</th>
      <th>Excuse</th>
  </tr>
  <% @attendance.each do |att| %>
      <tr>
        <td><%= att.training_event.training_date.to_s(:long_ordinal) %></td>
        <td><%= att.attendance %></td>
        <td><%= att.excuse %></td>

      </tr>

  <% end %>
</table>
<br>
<br>
<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>