config/routes.rb
Judesapp::Application.routes.draw do

  get 'sitemap' => "sitemap#index"

    root :to => 'pages#home'
    get "pages/home"
    get "pages/about"
    get "sessions/new"
    get 'login'  => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy' , :as => :logout
    get 'signup' => 'users#new'
    get "pages/sign_in"
    get "pages/help"

  resources :users
  resources :training_events
  resources :attends
  resources :players
  resources :session, :only => [:new, :create, :destroy]
  resources :sitemaps

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

end

app/models/attend.rb
class Attend < ActiveRecord::Base
	# player_id, training_event_id, attendance and excuse 
	
	attr_accessible :training_event_id, :player_id, :attendance, :excuse

  validates :player_id, presence: true
  validates :training_event_id, presence: true

	belongs_to :training_event
	belongs_to :player
	
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController

#  authenticate :user do
#    resources :attends, only: [:new, :create, :edit, :update, :destroy]
#  end



  # GET /attends
  # GET /attends.json
  def index
    @attends = Attend.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json; @attends }
    end
  end

  def player
    player = Player.find(:player_id)
  end

  def training_event
    @training_event = TrainingEvent.find(:player_id)
  end
  # GET /attends/1
  # GET /attends/1.json
  def show
    @attend = Attend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json; @attend }
    end
  end

  # GET /attends/new
  # GET /attends/new.json
  def new
    @attend = Attend.new
	
	
		#======================
	@all_training_events = TrainingEvent.all
	@all_players = Player.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attend }
    end
  end

  # GET /attends/1/edit
  def edit
    @attend = Attend.find(params[:id])
  end

  # POST /attends
  # POST /attends.json
  def create
    @attend = Attend.new(params[:attend])

    respond_to do |format|
      if @attend.save
        format.html { redirect_to @attend, notice: 'Attend was successfully created.' }
        format.json { render json: @attend, status: :created, location: @attend }
      else
        format.html { render action: "new" }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attends/1
  # PUT /attends/1.json
  def update
    @attend = Attend.find(params[:id])

    respond_to do |format|
      if @attend.update_attributes(params[:attend])
        format.html { redirect_to @attend, notice: 'Attend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attends/1
  # DELETE /attends/1.json
  def destroy
    @attend = Attend.find(params[:id])
    @attend.destroy

    respond_to do |format|
      format.html { redirect_to attends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/views/attends/_form.html.erb
<%= form_for(@attend) do |f| %>
  <% if @attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attend.errors.count, "error") %> prohibited this attend from being saved:</h2>
      <ul>
      <% @attend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div align="center">
      
        <div class="field">
        <%= f.label "Player" %><br />
          <%= f.collection_select :player_id, Player.all, :id, :name %>
        </div>

        <div class="field">
            <%= f.label 'Training Date' %><br />
          <%= f.collection_select :training_event_id, TrainingEvent.all, :id, :training_date  %>
        </div>
        <div class="field">
        <%= f.label :attendance %><br />
        <%= f.check_box :attendance %>
        </div>
        <div class="field">
        <%= f.label :excuse %><br />
        <%= f.text_field :excuse %>
        </div>
        <div class="actions">
        <%= f.submit %>
        </div>
    <% end %>
</div>

app/views/attends/_formNew.html.erb
<%= form_for(@attend) do |f| %>
  <% if @attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attend.errors.count, "error") %> prohibited this attend from being saved:</h2>
      <ul>
      <% @attend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div align="center" >
      <div style="width: 50%; height: 50%; background-color: white;" class="round">
        <br>
        <div align="center" class="field" >

          <%= f.collection_select :player_id, Player.all, :id, :name, {:prompt => 'Select Player'} %>

          <%= f.collection_select :training_event_id, TrainingEvent.all, :id, :training_date, {:prompt => 'Select Training Date'}  %>
          <%= f.label "Attended" %><br />
          <%= f.check_box :attendance %><br><br>
          <%= f.text_field :excuse, :placeholder => "Excuse" %>

        </div>
        <div class="actions">
        <%= f.submit %>
        </div>
        </div>
    <% end %>
</div>

app/views/attends/_formUpdate.html.erb
<%= form_for(@attend) do |f| %>
  <% if @attend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attend.errors.count, "error") %> prohibited this attend from being saved:</h2>
      <ul>
      <% @attend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div align="center" >
      <div style="width: 50%; height: 50%; background-color: white;" class="round">
        <br>
        <div align="center" class="field" >

          <%= f.collection_select :player_id, Player.all, :id, :name, {:prompt => 'Select Player'} %>

          <%= f.collection_select :training_event_id, TrainingEvent.all, :id, :training_date, {:prompt => 'Select Training Date'}  %>
          <%= f.label "Attended" %><br />
          <%= f.check_box :attendance %><br><br>
          <%= f.text_field :excuse, :placeholder => "Excuse" %>

        </div>
        <div class="actions">
            <%= f.submit "Update Attendance" %>
        </div>
      </div>
    <% end %>
    </div>

app/views/attends/edit.html.erb
<br>
<h1>Editing Attendance</h1>

<%= render 'formUpdate' %>

<%= link_to 'Show', @attend %> |
<%= link_to 'Back', attends_path %>

app/views/attends/index.html.erb
<br>
<h1>Listing Attendance</h1>

<table id="listing">
  <tr>
    <th>Training Date</th>
    <th>Player</th>
    <th>Attendance</th>
    <th>Excuse</th>
    <th></th>
    <th></th>
  </tr>

<% @attends.each do |attend| %>
      <tr class="<%= cycle("odd_row", "even_row", name: "row_class") -%>">
    <td><%= attend.training_event.training_date %></td>
    <td><%= attend.player.name %></td>
    <td><%= attend.attendance %></td>
    <td><%= attend.excuse %></td>
    <td><%= link_to 'Edit', edit_attend_path(attend) %></td>
    <td><%= link_to 'Destroy', attend, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendance Record', new_attend_path %>

app/views/attends/new.html.erb
<br>
<br><h1>New Attendance Record</h1>

<%= render 'formNew' %>

<%= link_to 'Back', attends_path %>

app/views/attends/show.html.erb
<br>
<br><p id="notice"><%= notice %></p>

<p>
  <b>Player</b>
  <%= @attend.player.name %>
</p>

<p>
  <b>Training Date</b>
  <%= @attend.training_event.training_date %>
</p>

<p>
  <b>Attendance:</b>
  <%= @attend.attendance %>
</p>

<p>
  <b>Excuse:</b>
  <%= @attend.excuse %>
</p>


<%= link_to 'Edit', edit_attend_path(@attend) %> |
<%= link_to 'Back', attends_path %>