config/routes.rb
Judesapp::Application.routes.draw do

  get 'sitemap' => "sitemap#index"

    root :to => 'pages#home'
    get "pages/home"
    get "pages/about"
    get "sessions/new"
    get 'login'  => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy' , :as => :logout
    get 'signup' => 'users#new'
    get "pages/sign_in"
    get "pages/help"

  resources :users
  resources :training_events
  resources :attends
  resources :players
  resources :session, :only => [:new, :create, :destroy]
  resources :sitemaps

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

end

app/views/layouts/_footer.erb
<footer class="footer">
  <small>
    <a href="http://www.stjudesgaa.ie">The St Judes Camogie Application</a>
    by <a href="http://www.stjudesgaa.ie/">Oisin O'Donnell C10345787</a>
  </small>
</footer>

app/views/layouts/_header.erb
<header>
   <style>
      background: <%= image_tag('BlueBackground.png') %>
  </style>
  <div class="container">


    <%= image_tag("Judes Banner.png", :alt => "Judes App") %>

    <div class="container" style="width: 100%; height: 100%; background-color: white;" class="round">

        <% if not current_user.nil? %>
            <b>Welcome <%= current_user_logged_in %>:</b>
        <% else %>
            <b> </b><br>
        <% end %>

        <table id="navigation1">

          <% if not current_user.nil? %>

              <th align="left"><%= link_to "Users", users_path %></th>
              <th align="center"><%= link_to "Players", players_path %></th>
              <th align="center"><%= link_to "Training Events", training_events_path %></th>
              <th align="center"><%= link_to "Attendance", attends_path %></th>
              <th align="center"><%= link_to "My Profile", current_user %></th>
              <th align="center"><%= link_to "Sitemap", sitemaps_path %></th>
              <th align="right"><%= link_to "Sign-Out", logout_path, :method => :delete %></th>
          <% else %>
              <th align="center"><%= link_to "Sign-In", login_path %></th>
          <% end %>
        </table>

    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <%= javascript_include_tag :defaults %>
      <title>St Judes Management Application</title>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'applications', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </head>

    <body>
        <%= render "layouts/header" %>

        <div class="container">

          <section class="round">
            <%= yield %>
          </section>

        </div>
        <%= render "layouts/footer" %>
    </body>
</html>